### ISSUE TITLE
Update with changes from changes from kubernetes #29930

### ISSUE THREAD

**Issue by drshade** [uruddarraju/kubernetes-rbac-policies#3]
This project is awesome - thank you. It has really helped me bed down my RBAC policies by comparing against yours. 

The change introduced by https://github.com/kubernetes/kubernetes/pull/29930 has broken the way that nonResourceURLs work, and can now no-longer be associated with resources.

Would you like me to fork and create a pull request?

**Comment by gianrubio** [comment]
@drshade take a look on #2
